######################################################################
# Automatically generated by qmake (3.1) Fri Jul 3 21:03:06 2026
######################################################################

TEMPLATE = app
TARGET = Snake-Widget
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
HEADERS += snake_widget.h \
           config/config/snake_widget.h \
           build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/include/ui_snake_widget.h \
           config/config/config/config/snake_widget.h \
           config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/include/ui_snake_widget.h \
           config/config/config/config/config/config/snake_widget.h \
           config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/include/ui_snake_widget.h \
           config/config/config/config/config/config/config/config/snake_widget.h \
           config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/include/ui_snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/snake_widget.h \
           config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/include/ui_snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/include/ui_snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/include/ui_snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/include/ui_snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/include/ui_snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/include/ui_snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/include/ui_snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/include/ui_snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/include/ui_snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/include/ui_snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/include/ui_snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/include/ui_snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/include/ui_snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/include/ui_snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/include/ui_snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/include/ui_snake_widget.h \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/include/ui_snake_widget.h
FORMS += snake_widget.ui \
         config/config/snake_widget.ui \
         config/config/config/config/snake_widget.ui \
         config/config/config/config/config/config/snake_widget.ui \
         config/config/config/config/config/config/config/config/snake_widget.ui \
         config/config/config/config/config/config/config/config/config/config/snake_widget.ui \
         config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.ui \
         config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.ui \
         config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.ui \
         config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.ui \
         config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.ui \
         config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.ui \
         config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.ui \
         config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.ui \
         config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.ui \
         config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.ui \
         config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.ui \
         config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.ui \
         config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.ui \
         config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.ui \
         config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.ui
SOURCES += main.cpp \
           snake_widget.cpp \
           config/config/main.cpp \
           config/config/snake_widget.cpp \
           build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/mocs_compilation.cpp \
           config/config/config/config/main.cpp \
           config/config/config/config/snake_widget.cpp \
           build/Desktop_Qt_6_11_1_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/mocs_compilation.cpp \
           config/config/config/config/config/config/main.cpp \
           config/config/config/config/config/config/snake_widget.cpp \
           config/config/build/Desktop_Qt_6_11_1_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/mocs_compilation.cpp \
           config/config/config/config/config/config/config/config/main.cpp \
           config/config/config/config/config/config/config/config/snake_widget.cpp \
           config/config/config/config/build/Desktop_Qt_6_11_1_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/mocs_compilation.cpp \
           config/config/config/config/config/config/config/config/config/config/main.cpp \
           config/config/config/config/config/config/config/config/config/config/snake_widget.cpp \
           config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/mocs_compilation.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/main.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.cpp \
           config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/mocs_compilation.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/main.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.cpp \
           config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/mocs_compilation.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/main.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/mocs_compilation.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/main.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/mocs_compilation.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/main.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/mocs_compilation.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/main.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/mocs_compilation.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/main.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/mocs_compilation.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/main.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/mocs_compilation.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/main.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/mocs_compilation.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/main.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/mocs_compilation.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/main.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/mocs_compilation.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/main.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/mocs_compilation.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/main.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/mocs_compilation.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/main.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/mocs_compilation.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/main.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/snake_widget.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/mocs_compilation.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/Snake-Widget_autogen/mocs_compilation.cpp \
           config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/build/Desktop_Qt_6_11_1_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp
TRANSLATIONS += Snake-Widget_en_US.ts \
                config/config/Snake-Widget_en_US.ts \
                config/config/config/config/Snake-Widget_en_US.ts \
                config/config/config/config/config/config/Snake-Widget_en_US.ts \
                config/config/config/config/config/config/config/config/Snake-Widget_en_US.ts \
                config/config/config/config/config/config/config/config/config/config/Snake-Widget_en_US.ts \
                config/config/config/config/config/config/config/config/config/config/config/config/Snake-Widget_en_US.ts \
                config/config/config/config/config/config/config/config/config/config/config/config/config/config/Snake-Widget_en_US.ts \
                config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/Snake-Widget_en_US.ts \
                config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/Snake-Widget_en_US.ts \
                config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/Snake-Widget_en_US.ts \
                config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/Snake-Widget_en_US.ts \
                config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/Snake-Widget_en_US.ts \
                config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/Snake-Widget_en_US.ts \
                config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/Snake-Widget_en_US.ts \
                config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/Snake-Widget_en_US.ts \
                config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/Snake-Widget_en_US.ts \
                config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/Snake-Widget_en_US.ts \
                config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/Snake-Widget_en_US.ts \
                config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/Snake-Widget_en_US.ts \
                config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/Snake-Widget_en_US.ts
